sonar.projectKey=MedicitasFrontend
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.jsx,**/*.test.js
# Cobertura generada por Vitest (reporter lcov)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/main.jsx,src/test/**,**/*.test.*
sonar.exclusions=dist/**,node_modules/**,coverage/**
