import { useState } from 'react'
import { Eye, Pencil, Trash2, UserRound } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogMedia, AlertDialogTitle } from '@/components/ui/alert-dialog'
import { useSession } from '@/features/auth'
import { patientsClient } from '@/features/patients/api/patients-api'
import { patientKeys, useDeletePatient } from '@/features/patients/hooks/use-patient-mutations'
import { EntityList } from '@/shared/crud'
const date = new Intl.DateTimeFormat('es-PE', { dateStyle: 'medium' })
export default function PatientsListPage() { const navigate = useNavigate(); const { data: session } = useSession(); const remove = useDeletePatient(); const [selected, setSelected] = useState(null); const columns = [{ key: 'documentId', label: 'Documento', sortable: true, render: (item) => <span className="font-medium">{item.documentId}</span> }, { key: 'firstName', label: 'Paciente', sortKey: 'user.firstName', sortable: true, render: (item) => `${item.firstName} ${item.lastName}` }, { key: 'email', label: 'Correo' }, { key: 'phone', label: 'Teléfono' }, { key: 'dateOfBirth', label: 'Nacimiento', render: (item) => item.dateOfBirth ? date.format(new Date(`${item.dateOfBirth}T00:00:00`)) : '—' }]; const actions = [{ action: 'Read', label: 'Ver detalle', icon: Eye, onClick: (item) => navigate(`/dashboard/pacientes/${item.id}`) }, { action: 'Update', label: 'Editar', icon: Pencil, onClick: (item) => navigate(`/dashboard/pacientes/${item.id}/editar`) }, { action: 'Delete', label: 'Desactivar', icon: Trash2, variant: 'destructive', onClick: setSelected }]; async function confirmDelete() { try { await remove.mutateAsync(selected.id); setSelected(null) } catch { /* mantiene dialogo */ } } return <><EntityList title="Pacientes" description="Administra perfiles clínicos y cuentas de acceso de pacientes." icon={UserRound} queryKey={patientKeys.all} client={patientsClient} columns={columns} defaultSortBy="documentId" searchPlaceholder="Buscar por documento, nombre o apellido..." createLabel="Registrar paciente" onCreate={() => navigate('/dashboard/pacientes/nuevo')} actions={actions} permissionPrefix="Patient" permissions={session.permissions} /><AlertDialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}><AlertDialogContent><AlertDialogHeader><AlertDialogMedia><Trash2 /></AlertDialogMedia><AlertDialogTitle>¿Desactivar este paciente?</AlertDialogTitle><AlertDialogDescription>El perfil de {selected?.firstName} {selected?.lastName} dejará de aparecer en los listados clínicos.{remove.error && <span className="mt-2 block text-destructive">{remove.error.message}</span>}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={remove.isPending}>Cancelar</AlertDialogCancel><AlertDialogAction variant="destructive" disabled={remove.isPending} onClick={confirmDelete}>{remove.isPending ? 'Desactivando...' : 'Desactivar'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></> }
