import { ShoppingCart } from 'lucide-react'
import { useNavigate, useParams } from 'react-router-dom'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { useSession } from '@/features/auth'
import { ordersClient } from '@/features/orders/api/orders-api'
import { orderKeys } from '@/features/orders/hooks/use-order-mutations'
import { EntityDetail } from '@/shared/crud'
const money = new Intl.NumberFormat('es-PE', { style: 'currency', currency: 'PEN' }); const date = new Intl.DateTimeFormat('es-PE', { dateStyle: 'long', timeStyle: 'short' })
export default function OrderDetailPage() { const { id } = useParams(); const navigate = useNavigate(); const { data: session } = useSession(); const fields = [{ key: 'patientName', label: 'Cliente', render: (item) => item.patientName || 'Venta directa' }, { key: 'createdAt', label: 'Fecha y hora', render: (item) => date.format(new Date(item.createdAt)) }, { key: 'total', label: 'Total cobrado', render: (item) => money.format(item.total) }, { key: 'items', label: 'Detalle de productos', colSpan: 2, render: (item) => <div className="overflow-hidden rounded-lg border"><Table><TableHeader><TableRow><TableHead>Producto</TableHead><TableHead className="text-right">Cant.</TableHead><TableHead className="text-right">P. unitario</TableHead><TableHead className="text-right">Subtotal</TableHead></TableRow></TableHeader><TableBody>{item.items.map((line) => <TableRow key={line.productId}><TableCell>{line.productName}</TableCell><TableCell className="text-right">{line.quantity}</TableCell><TableCell className="text-right">{money.format(line.unitPrice)}</TableCell><TableCell className="text-right font-medium">{money.format(line.subtotal)}</TableCell></TableRow>)}</TableBody></Table></div> }]; return <EntityDetail id={id} queryKey={orderKeys.all} client={ordersClient} title="Comprobante de venta" description="Detalle de productos, cantidades e importe registrado." icon={ShoppingCart} fields={fields} onBack={() => navigate('/dashboard/ventas')} permissionPrefix="Order" permissions={session.permissions} /> }
